let funnyQuotes = [
    "I am swift as a gazelle. An old one. With arthritis. Run over by a Land Rover. 8 days ago.",
    "I asked God for a bike, but I know God doesn’t work that way. So I stole a bike and asked for forgiveness.",
    "I didn’t fall down. I did attack the floor, though.",
    "I don’t need a hair stylist, my pillow gives me a new hairstyle every morning.",
    "I don’t suffer from insanity, I enjoy every minute of it.",
    "I get enough exercise pushing my luck.",
    "I had loads to do today. Ah well, so now I have loads to do tomorrow.",
    "I like to be an optimist. It pisses people off.",
    "I read married couples have sex about 74 times per year. It’s the end of November now. Seems I’m going to have a seriously exciting December!",
    "I refuse to answer that question on the grounds that I don’t know the answer.",
    "I refuse to have a battle of wits with an opponent so clearly unarmed.",
    "A train station is where the train stops. A bus station is where the bus stops. On my desk, I have a work station…",
    "A true optimist is the guy who falls off a skyscraper and after 50 floors thinks to himself – well, so far so good!",
    "According to my mirror I am pregnant. The father is Nutella.",
    "After millions of years of evolution, you’re kind of a disappointment.",
    "Alcohol does not solve any problems, but then again, neither does milk.",
    "Alcohol! Because no great story started with someone eating a salad.",
    "All my life I thought air was for free. That was until I bought a bag of potato chips.",
    "I speak fluent ironic with a solid sarcastic accent.",
    "I am in touch with my motivation. I saw it going by this morning, waving at me and winking.",
    "I am nobody. Nobody is perfect. I am perfect.",
    "I think the worst time to have a heart attack is during a game of charades.",
    "I used to think that you were a pain in the neck. My opinion of you has dropped significantly lower since then."];
    export { funnyQuotes };